### ISSUE TITLE
Can't connect to Docker API server on Windows

### ISSUE THREAD

**Issue by karolz-ms** [docker-archive-public/docker.node-sdk-legacy#11]
Repro steps:

1. Install Docker Desktop Edge 45896
1. Run the following example

```typescript
import { Contexts } from "@docker/sdk";
import {
  ListRequest,
  ListResponse,
} from "@docker/sdk/dist/contexts";

// On Windows this is the endpoint the API server listens on (Docker Desktop Edge 45896)
const addr = 'npipe:////./pipe/dockerCliApi';

const client = new Contexts(addr);

// Get the list of contexts
client.list(new ListRequest(), (err: any, resp: ListResponse) => {
    if (err) {
        console.error(err);
        return;
    }

    const contexts = resp
        .getContextsList()
        .map((c) => new Contexts(c.getName()));

    console.log(contexts);
});
```

Expected: should see the list of Docker context names

Actual:

```
C:\code\docker-node-sdk-play>npx ts-node listContexts.ts

C:\code\docker-node-sdk-play\node_modules\@grpc\grpc-js\src\resolver-dns.ts:276
      throw new Error(`Failed to parse target ${uriToString(target)}`);
            ^
Error: Failed to parse target dns:npipe:////./pipe/dockerCliApi
    at Function.getDefaultAuthority (C:\code\docker-node-sdk-play\node_modules\@grpc\grpc-js\src\resolver-dns.ts:276:13)
    at Object.getDefaultAuthority (C:\code\docker-node-sdk-play\node_modules\@grpc\grpc-js\src\resolver.ts:129:47)
    at new ChannelImplementation (C:\code\docker-node-sdk-play\node_modules\@grpc\grpc-js\src\channel.ts:184:31)
    at new Client (C:\code\docker-node-sdk-play\node_modules\@grpc\grpc-js\src\client.ts:146:30)
    at new ServiceClientImpl (C:\code\docker-node-sdk-play\node_modules\@grpc\grpc-js\src\make-client.ts:119:3)
    at new Contexts (C:\code\docker-node-sdk-play\node_modules\@docker\sdk\src\index.ts:22:5)
    at Object.<anonymous> (C:\code\docker-node-sdk-play\listContexts.ts:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module.m._compile (C:\code\docker-node-sdk-play\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

This makes the SDK pretty much busted on Windows 😞 

@gtardif FYI

**Comment by gtardif** [comment]
Hi Karol, 
For some reason, the syntax to connect to npipe using the grpc-js library is : 
`unix:////./pipe/dockerCliApi`
Also, you should be able to not specify this address and simply `const client = new Contexts();`
The sdk should have the right defaults based on OS

**Comment by gtardif** [comment]
Ah, digging a bit more and looking at other issues you opened, this was fixed in the sources, but not in the proto generated stuff (/dist), https://github.com/docker/node-sdk/pull/13 should fix that

**Comment by karolz-ms** [comment]
It works now, thanks ☺️
