### ISSUE TITLE
google-auth-library needs to be added back to dependencies

### ISSUE THREAD

**Issue by bwateratmsft** [docker-archive-public/docker.node-sdk-legacy#24]
Webpack is failing due to this error:
```
ERROR in ./node_modules/@grpc/grpc-js/build/src/channel-credentials.js
Module not found: Error: Can't resolve 'google-auth-library' in 'D:\vscode-docker\node_modules\@grpc\grpc-js\build\src'
[15:34:00] 'webpackProdTask' errored after 1.22 min
[15:34:00] Error: exited with error code: 2
    at ChildProcess.onexit (D:\vscode-docker\node_modules\end-of-stream\index.js:40:36)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

I believe that means `google-auth-library` needs to be added back to `dependencies`.

**Comment by rumpl** [comment]
Argh sorry about that. Will fix quickly

**Comment by bwateratmsft** [comment]
No worries :smile:

Thanks!
