### ISSUE TITLE
ps example error on unknown context

### ISSUE THREAD

**Issue by metcalfc** [docker-archive-public/docker.node-sdk-legacy#7]
Happens on both Mac and WSL2.

```
> @docker/sdk@0.1.0 example /Users/metcalfc/src/node-sdk
> ts-node -O '{"module": "CommonJS"}' "examples/ps.ts"


/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call.ts:81
  return Object.assign(new Error(message), status);
                       ^
Error: 2 UNKNOWN: context "default": not found
    at Object.callErrorFromStatus (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    at Object.onReceiveStatus (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
    at Object.onReceiveStatus (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
    at Http2CallStream.outputStatus (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call-stream.ts:230:22)
    at Http2CallStream.maybeOutputStatus (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call-stream.ts:280:14)
    at Http2CallStream.endCall (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call-stream.ts:263:12)
    at Http2CallStream.handleTrailers (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call-stream.ts:412:10)
    at ClientHttp2Stream.<anonymous> (/Users/metcalfc/src/node-sdk/node_modules/@grpc/grpc-js/src/call-stream.ts:467:16)
    at ClientHttp2Stream.emit (events.js:315:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @docker/sdk@0.1.0 example: `ts-node -O '{"module": "CommonJS"}' "examples/ps.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @docker/sdk@0.1.0 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by rumpl** [comment]
If you create an ACI context and set it as default the `ps` example will work. The api doesn't know how to handle the "classic" contexts.

I'll change the example to be less brittle and update its documentation.
